const SocialIcons = [
    {
        id:'facebook',
        img:'./assets/images/icons/social/facebook.svg',
        link:'#'
    },
    {
        id:'twitter',
        img:'./assets/images/icons/social/twitter.svg',
        link:'#'
    },
    {
        id:'linkedin',
        img:'./assets/images/icons/social/linkedin.svg',
        link:'#'
    },
    {
        id:'youtube',
        img:'./assets/images/icons/social/youtube.svg',
        link:'#'
    },
    {
        id:'instagram',
        img:'./assets/images/icons/social/instagram.svg',
        link:'#'
    },
    {
        id:'googleplus',
        img:'./assets/images/icons/social/googleplus.svg',
        link:'#'
    },
    {
        id:'pinterest',
        img:'./assets/images/icons/social/pinterest.svg',
        link:'#'
    },
    {
        id:'rss',
        img:'./assets/images/icons/social/rss.svg',
        link:'#'
    }
]

export default SocialIcons